package com.filipe.feedback_analyzer.dto;

public enum FeatureCode {
    EDITAR_PERFIL,
    VER_CURSOS,
    INSCREVER_CURSO,
    CANCELAR_INSCRICAO,
    AVALIAR_CURSO,
    COMPRAR_CURSO,
    ACESSAR_CONTEUDO,
    SUPORTE_TECNICO,
    ALTERAR_SENHA,
    RECUPERAR_CONTA,
    EDITAR_PREFERENCIAS_NOTIFICACAO,
    CONSULTAR_HISTORICO;
}
